#' CPAD data pipeline, targets edition.
#'
#' A make-like pipeline built on the {targets} package. Gives proper
#' dependency tracking: change one raw CSV (or an import module) and
#' only the affected downstream parquet files rebuild.
#'
#' Layout:
#'   db/<name>.parquet            canonical "final" version of each source
#'   db/stages/raw/*.parquet      stage 1 intermediates (CSV -> parquet)
#'   db/stages/keyed/*.parquet    stage 2 intermediates (UID joined)
#'   private/officer.parquet      officer UID table
#'
#' Each source's last stage writes directly to db/<name>.parquet, so the
#' canonical output is always at the same flat path regardless of how many
#' stages that source goes through:
#'   beat, roster                  (1 stage)   -> db/<name>.parquet
#'   assignment, military, warrant (2 stages)  -> db/<name>.parquet
#'   arrest, contact, force, stop  (3 stages)  -> db/<name>.parquet
#'
#' The pipeline is fully spec-driven: every target is generated by looping
#' over `spec$sources()`. Adding or reclassifying a source means editing
#' that table — no edits to this file.
#'
#' Usage (prefer ./make.sh — it filters a benign polars stderr warning
#' that can't be suppressed from R):
#'   ./make.sh                # build everything
#'   ./make.sh outdated       # what's stale
#'   ./make.sh visnetwork     # inspect DAG
#'   ./make.sh destroy        # nuke targets metadata
#' Or directly:
#'   Rscript -e 'targets::tar_make()'
library(targets)

# {targets} always runs with the project root as cwd, so getwd() is the
# right value here and makes the file portable across machines.
options(box.path = getwd())

box::use(
  fs[dir_create],
  import/arrest,
  import/assignment,
  import/beat,
  import/contact,
  import/force,
  import/military,
  import/roster,
  import/stop,
  import/warrant,
  proc/officer,
  proc/uid,
  proc/aid,
  proc/spec
)

tar_option_set(
  envir = globalenv(),
  format = "file"
)

# ---------------------------------------------------------------------------
# Sink helpers.
# ---------------------------------------------------------------------------

#' Sink a lazy frame to parquet and return its path (for {targets}
#' format = "file" tracking). Ensures the parent dir exists.
sink_lf <- function(lf, out_path) {
  dir_create(dirname(out_path))
  lf$sink_parquet(out_path)
  out_path
}

#' Same, but for the officer table, which is eagerly collected before
#' writing so the `unique`/`group_by` pipeline in officer$generate_key
#' materializes cleanly.
sink_officer <- function(paths, out_path) {
  dir_create(dirname(out_path))
  officer$generate_key(paths = paths)$collect()$write_parquet(out_path)
  out_path
}

# ---------------------------------------------------------------------------
# Pipeline — generated from spec$sources().
#
# Per source we emit:
#   raw_<name>              always
#   keyed_<name>            iff spec$key != "none"
#   event_<name>            iff spec$event
#
# Target names are bare symbols; tar_target_raw + substitute preserves the
# symbols in each command so {targets} can see the edges via codetools.
# ---------------------------------------------------------------------------

specs <- spec$sources()

raw_targets <- lapply(specs, function(s) {
  tar_target_raw(
    paste0("raw_", s$name),
    substitute(
      sink_lf(MOD$build(), P),
      list(MOD = as.symbol(s$name), P = spec$raw_path(s))
    )
  )
})

# Officer UID table depends on every raw_* target. Passing them as an
# explicit `c(raw_arrest, raw_assignment, ...)` call both (a) registers
# the deps and (b) hands the file paths straight to sink_officer.
raw_syms <- lapply(specs, function(s) as.symbol(paste0("raw_", s$name)))
officer_target <- tar_target_raw(
  "officer_parquet",
  substitute(
    sink_officer(PATHS, "private/officer.parquet"),
    list(PATHS = as.call(c(list(quote(c)), raw_syms)))
  )
)

keyed_targets <- lapply(Filter(function(s) s$key != "none", specs), function(s) {
  raw_sym <- as.symbol(paste0("raw_", s$name))
  out_path <- spec$keyed_path(s)
  cmd <- if (identical(s$key, "regular")) {
    substitute(
      sink_lf(uid$join(IN, ON, officer_path = officer_parquet), OUT),
      list(IN = raw_sym, ON = s$on, OUT = out_path)
    )
  } else {  # "asof"
    substitute(
      sink_lf(uid$join_asof(IN, by = BY, officer_path = officer_parquet), OUT),
      list(IN = raw_sym, BY = s$by, OUT = out_path)
    )
  }
  tar_target_raw(paste0("keyed_", s$name), cmd)
})

# AID stage pulls in keyed_assignment regardless of which event source it
# belongs to; that's how the asof-join lines up events with shifts.
event_targets <- lapply(Filter(function(s) s$event, specs), function(s) {
  keyed_sym <- as.symbol(paste0("keyed_", s$name))
  out_path <- spec$event_path(s)
  tar_target_raw(
    paste0("event_", s$name),
    substitute(
      sink_lf(aid$join_asof(IN, assignment_path = keyed_assignment), OUT),
      list(IN = keyed_sym, OUT = out_path)
    )
  )
})

c(raw_targets, list(officer_target), keyed_targets, event_targets)
