import polars.selectors as cs
import polars as zl

def scan(path):
    df = (
        zl.scan_csv(
          path,
          infer_schema_length=0,
          null_values=["", " "],
          dtypes={
            "created_dt": zl.Datetime,
            "modified_dt": zl.Datetime,
            "first.appointed": zl.Date,
            "second.appointed": zl.Date,
            "supervisor.appointed": zl.Date,
            "gang_lookout": zl.Categorical,
            "gang_narcotic_related": zl.Categorical,
            "gang_other": zl.Categorical,
            "gang_security": zl.Categorical,
            "intimidation": zl.Categorical,
            "name_verified": zl.Categorical,
            "completion": zl.Categorical,
            "handcuffed": zl.Categorical,
            "vehicle_involved": zl.Categorical,
            "suspect_narcotic_activity": zl.Categorical,
            "enforcement_action_taken": zl.Categorical,
            "indicative_casing": zl.Categorical,
            "fits_description_offender": zl.Categorical,
            "other_factor": zl.Categorical,
            "pat_down": zl.Categorical,
            "pat_down_consent": zl.Categorical,
            "pat_down_receipt_given": zl.Categorical,
            "verbal_threats": zl.Categorical,
            "knowledge_of_prior": zl.Categorical,
            "actions_indicative_violence": zl.Categorical,
            "violent_crime": zl.Categorical,
            "suspicious_object": zl.Categorical,
            "other_reasonable_suspicion": zl.Categorical,
            "weapons_or_contraband_found": zl.Categorical,
            "firearm": zl.Categorical,
            "cocaine": zl.Categorical,
            "heroin": zl.Categorical,
            "other_contraband": zl.Categorical,
            "other_weapon": zl.Categorical,
            "cannabis": zl.Categorical,
            "other_controlled_substance": zl.Categorical,
            "search": zl.Categorical,
            "search_contraband_found": zl.Categorical,
            "search_firearm": zl.Categorical,
            "search_cocaine": zl.Categorical,
            "search_heroin": zl.Categorical,
            "search_other_contraband": zl.Categorical,
            "search_cannabis": zl.Categorical,
            "search_other_controlled_substance": zl.Categorical,
            "para": zl.Categorical,
            "search_consent": zl.Categorical,
            "search_other_weapon": zl.Categorical,
            "search_property": zl.Categorical,
            "stolen_property": zl.Categorical,
            "search_alcohol": zl.Categorical,
            "search_other": zl.Categorical,
            "search_para": zl.Categorical,
            "search_stolen_property": zl.Categorical,
            "vehicle_stopped": zl.Categorical,
            "proximity_to_crime": zl.Categorical,
            "body_camera": zl.Categorical,
            "car_camera": zl.Categorical,
            "information_refused": zl.Categorical,
            "alcohol": zl.Categorical,
          },
          new_columns=[
            "uid_contact",
            "contact_type",
            "contact_type_description",
            "card",
            "dt",
            "first.last_name",
            "first.middle_initial",
            "first.first_name",
            "first.star",
            "first.appointed",
            "first.gender",
            "first.race",
            "first.yob",
            "second.last_name",
            "second.middle_initial",
            "second.first_name",
            "second.star",
            "second.appointed",
            "second.gender",
            "second.race",
            "second.yob",
            "supervisor.last_name",
            "supervisor.middle_initial",
            "supervisor.first_name",
            "supervisor.star",
            "supervisor.appointed",
            "supervisor.gender",
            "supervisor.race",
            "supervisor.yob",
            "civilian_clothing",
            "rd",
            "event",
            "event_assigneed_by_cd",
            "hotspot",
            "mission",
            "unit",
            "created_by",
            "created_dt",
            "modified_by",
            "modified_dt",
            "submitting_beat",
            "submitting_unit",
            "street_number",
            "street_direction",
            "street",
            "city",
            "state",
            "zip",
            "district",
            "sector",
            "beat",
            "area",
            "ward",
            "location",
            "civilian_age",
            "civilian_age_to",
            "civilian_gender",
            "civilian_race",
            "civilian_height",
            "civilian_weight",
            "civilian_build",
            "civilian_eye_color",
            "civilian_hair_color",
            "civilian_hairstyle",
            "civilian_complexion",
            "civilian_facial_hair",
            "residence_district",
            "residence_sector",
            "residence_beat",
            "residence_area",
            "residence_ward",
            "bus_area",
            "bus_beat",
            "bus_district",
            "bus_sector",
            "bus_ward",
            "gang_name",
            "faction_name",
            "gang_lookout",
            "gang_narcotic_related",
            "gang_other_name",
            "gang_other",
            "gang_security",
            "intimidation",
            "civilian_clothing_description",
            "name_verified",
            "completion",
            "contact_card_status",
            "vehicle_make",
            "vehicle_description",
            "vehicle_style",
            "vehicle_style_description",
            "vehicle_type",
            "vehicle_model",
            "vehicle_color_top",
            "vehicle_color_bottom",
            "handcuffed",
            "vehicle_involved",
            "dispersal_time",
            "number_of_persons_dispersed",
            "suspect_narcotic_activity",
            "enforcement_action_taken",
            "indicative_casing",
            "fits_description_offender",
            "other_factor",
            "pat_down",
            "pat_down_consent",
            "pat_down_receipt_given",
            "verbal_threats",
            "knowledge_of_prior",
            "actions_indicative_violence",
            "violent_crime",
            "suspicious_object",
            "other_reasonable_suspicion",
            "weapons_or_contraband_found",
            "firearm",
            "cocaine",
            "cocaine_amount",
            "heroin",
            "heroin_amount",
            "other_contraband",
            "other_contraband_description",
            "other_weapon",
            "other_weapon_description",
            "cannabis",
            "cannabis_amount",
            "other_controlled_substance",
            "other_controlled_substance_description",
            "other_controlled_substance_amount",
            "search",
            "search_contraband_found",
            "search_firearm",
            "search_cocaine",
            "search_cocaine_amount",
            "search_heroin",
            "search_heroin_amount",
            "search_other_contraband",
            "search_other_contraband_description",
            "search_cannabis",
            "search_cannabis_amount",
            "search_other_controlled_substance",
            "search_other_controlled_substance_description",
            "search_other_controlled_substance_amount",
            "other_description",
            "other_inventory_number",
            "other_weapon_inventory_number",
            "para",
            "para_inventory_number",
            "search_consent",
            "search_other_weapon_description",
            "search_other_weapon",
            "search_property",
            "stolen_property",
            "stolen_property_inventory_number",
            "search_alcohol",
            "search_alcohol_inventory_number",
            "search_firearm_inventory_number",
            "search_other_decription",
            "search_other",
            "search_other_inventory_number",
            "search_other_weapon_inventory_number",
            "search_para",
            "search_para_inventory_number",
            "search_stolen_property",
            "search_stolen_property_inventory_number",
            "vehicle_stopped",
            "vehicle_year",
            "proximity_to_crime",
            "body_camera",
            "car_camera",
            "information_refused",
            "cannabis_inventory_number",
            "cocaine_inventory_number",
            "heroin_inventory_number",
            "other_controlled_substance_inventory_number",
            "search_cannabis_inventory_number",
            "search_cocaine_inventory_number",
            "search_heroin_inventory_number",
            "search_other_controlled_substance_inventory_number",
            "firearm_inventory_number",
            "alcohol",
            "alcohol_inventory_number",
            "enforcement_type",
            "cited_violations",
            "enforcement_id",
          ],
      )
      .with_columns(
        zl.col("dt").str.strptime(zl.Datetime, format="%d-%b-%Y %H:%M"),
        zl.col(zl.Categorical).exclude(["dt"]).map_dict({"N":False, "Y":True})
      )
    )

    return df
